name: Python 3.11
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show files (debug)
        run: |
          pwd
          ls -la
          ls -la module01

      - name: Install dependencies
        working-directory: module01
        run: make install

      - name: Lint
        working-directory: module01
        run: make lint

      - name: Test
        working-directory: module01
        run: make test